[build]
  functions = 'functions/'

[context.production]
  environment = {
    JWT_USER="admin"
    JWT_PASS="sfdi40k2QOqaO"@JyOUZl&*WA
    OMNISEND_FUNCTION="https://saint-and-center-beta.netlify.com/.netlify/functions/omnisend"
    WOOCOMMERCE_KEY="ck_990f62c74b9f424eb1ecf8b6b1bd3a2b7e180c7a"
    WOOCOMMERCE_SECRET="cs_0c39f3c5f8db99d8f1493394fffadba7629215cd"
  }

[context.development]
  environment = {
    JWT_USER="admin"
    JWT_PASS="sfdi40k2QOqaO"@JyOUZl&*WA
    OMNISEND_FUNCTION="http://localhost:8000/.netlify/functions/omnisend"
    WOOCOMMERCE_KEY="ck_990f62c74b9f424eb1ecf8b6b1bd3a2b7e180c7a"
    WOOCOMMERCE_SECRET="cs_0c39f3c5f8db99d8f1493394fffadba7629215cd"
  }
